### ISSUE TITLE
XML save options

### ISSUE THREAD

**Issue by zaidka** [polotek/libxmljs#244]
There doesn't seem to be a way to set XML save options as provided by libxml2. The only available option is XML_SAVE_FORMAT which is exposed as a boolean argument to document.toString function. Other options such as XML_SAVE_NO_DECL and XML_SAVE_NO_EMPTY cannot be set.

**Comment by teleological** [comment]
Implemented in PR #326 / #341

**Comment by rc0x03** [comment]
PR #341 doesn't implement `Document.toString()`. Document options can be easily implement by coping over the same option code and using `xmlSaveTree` instead of `xmlDocDumpFormatMemoryEnc` (which doesn't have an options argument). It should also be noted that HTML serialization uses a different function entirely. The only option that isn't ignored by `htmlNodeDumpFormatOutput` is `format`. Most of the HTML document formatting options are defined at parse time via [htmlParserOption](http://www.xmlsoft.org/html/libxml-HTMLparser.html#htmlParserOption).

**Comment by teleological** [comment]
:+1:

**Comment by rc0x03** [comment]
Added in #378
