### ISSUE TITLE
Missing ability to create plain text nodes

### ISSUE THREAD

**Issue by lillem4n** [polotek/libxmljs#263]
Hello!

First, thanks for a great lib! I just replaced xmldom with this for a major performance boost! :D

However, I'm missing a very important part for my project; creating text nodes. As far as I understand I cannot change this: <foo>bar <a>some</a></foo> to <foo>bar <a>some</a> lol</foo>, since the new node is a plain text node. I believe the binding I need is this: http://xmlsoft.org/html/libxml-tree.html#xmlNewDocText

If I am mistaken, gain some stackoverflow points by answering my question here: http://stackoverflow.com/questions/26289359/how-to-create-text-node-in-libxmljs

Thanks alot! :)

**Comment by hildjj** [comment]
Any status on this?  I need something like addNextSibling in order to add text after a given node.  Use case: `<foo xmlns:xi='http://www.w3.org/2001/XInclude'>boo <xi:include href='testing' parse='text'/> baz</foo>`.  Alternately, in this case a binding to `xmlReplaceNode` that accepts text, element, or CDATA nodes would work for me.

**Comment by RobinQu** [comment]
+1

**Comment by polotek** [comment]
It looks like we never landed the attached PR. I'm going to fix it up and get it landed later this week.

**Comment by RobinQu** [comment]
Bravo!

**Comment by teleological** [comment]
Implemented in #351
