### ISSUE TITLE
how to pass XML_PARSE_HUGE option

### ISSUE THREAD

**Issue by vodp** [polotek/libxmljs#372]
Hello,

I'd like how to configure XML_PARSE_HUGE option for a installation? Some of website could not be parsed probably because overly deep hierarchy.

**Comment by defunctzombie** [comment]
How does this option work and where would you specify this?

**Comment by rc0x03** [comment]
This option causes libxml to ignore its built in depth limitations while parsing. It would be specified as an option for parseHtml or parseXml.

**Comment by defunctzombie** [comment]
Are we already setup to pass in parsing options or did we only add toString options?

@vodp able to make a PR for this?

**Comment by triccardi-systran** [comment]
xml parsing with parser options was added in e6505e90b51bdf4beb4847299b4379d5192b8304:
Just call `parseXml` with a second parameter:
```js
libxmljs.parseXml(xml, {huge: true});
```


However, it's missing for `parseHtml`. eb1a9b6140e19ddd273f88b4317b74b86dd107d0 did start to add options to the html parser, but not generically like for `parseXml`.

**Comment by defunctzombie** [comment]
@vodp does the solution described by @triccardi-systran solve your issue?

**Comment by rc0x03** [comment]
@defunctzombie this only solves the issue for xml documents. I think the best solution would be to add the the xml option lookup function to parseHtml, since html documents will share the same options as xml documents. Also, if possible, we should include an html option lookup function in the same pull request. This way we finally have all the htmlparseroptions implemented.
